services:
  - type: web
    name: skill-wallet-backend
    env: python
    buildCommand: pip install -r Backend/requirements.txt
    startCommand: cd Backend && uvicorn app_clean:app --host 0.0.0.0 --port $PORT
    disk:
      name: uploaded-files
      mountPath: /opt/render/project/src/Backend/uploaded_files
      sizeGB: 1

  - type: static
    name: skill-wallet-frontend
    buildCommand: cd Frontend && npm ci && npm run build
    publishPath: Frontend/dist
