services:
  - type: web
    name: skill-wallet-backend
    runtime: python
    repo: https://github.com/anusmitasen2005-lgtm/SkillWalletProject
    rootDir: Backend
    buildCommand: pip install -r requirements.txt
    startCommand: python db_init.py && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        value: sqlite:////app/Backend/uploaded_files/skillwallet.db
      - key: SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: "*"
    disk:
      name: uploaded_files
      mountPath: /app/Backend/uploaded_files
      sizeGB: 1
